export const configFields = [
	{
		type: 'dropdown',
		id: 'protocol',
		label: 'Protocol',
		width: 4,
		default: 'mqtt://',
		choices: [
			{ id: 'mqtt://', label: 'mqtt://' },
			{ id: 'mqtts://', label: 'mqtts://' },
			{ id: 'ws://', label: 'ws://' },
			{ id: 'wss://', label: 'wss://' },
		],
	},
	{
		type: 'textinput',
		id: 'broker_ip',
		width: 4,
		label: 'Broker (Hostname/IP)',
	},
	{
		type: 'number',
		id: 'port',
		width: 4,
		label: 'Port',
		default: 1883,
		min: 1,
		max: 65535,
	},
	{
		type: 'textinput',
		id: 'user',
		width: 6,
		label: 'Username',
	},
	{
		type: 'textinput',
		id: 'password',
		width: 6,
		label: 'Password',
	},
{
type: 'textinput',
id: 'clientId',
width: 6,
label: 'MQTT Client ID',
default: 'bitfocus-companion-mqtt',
},
{
type: 'checkbox',
id: 'cleanSession',
width: 6,
label: 'Clean Session',
default: true,
},
{
type: 'number',
id: 'keepalive',
width: 6,
label: 'Keepalive (seconds)',
default: 60,
min: 0,
},
{
type: 'number',
id: 'reconnectPeriod',
width: 6,
label: 'Reconnect period (ms)',
default: 1000,
min: 0,
},
{
type: 'number',
id: 'connectTimeout',
width: 6,
label: 'Connect timeout (ms)',
default: 30000,
min: 0,
},
{
type: 'checkbox',
id: 'rejectUnauthorized',
width: 6,
label: 'Reject unauthorized TLS certificates',
default: true,
},
{
type: 'textinput',
id: 'tlsServername',
width: 6,
label: 'TLS server name (SNI)',
hint: 'Optional override when broker certificate CN does not match host',
},
{
type: 'textinput',
id: 'willTopic',
width: 12,
label: 'Last Will Topic',
},
{
type: 'textinput',
id: 'willPayload',
width: 12,
label: 'Last Will Payload',
},
{
type: 'number',
id: 'willQos',
width: 6,
label: 'Last Will QoS',
default: 0,
min: 0,
max: 2,
},
{
type: 'checkbox',
id: 'willRetain',
width: 6,
label: 'Last Will Retain',
default: false,
},
{
type: 'checkbox',
id: 'restartOnError',
width: 6,
label: 'Restart module on connection error',
		default: true,
	}
]
